name: DD-D1-sync
on:
  schedule:
    - cron: '14 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-DD-D1-2020scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync DD-D1-2020scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/DD-D1/2020scripts.git"
          source_branch: "master"
          destination_branch: "DD-D1"
          github_token: ${{ secrets.PAT }}
