name: passerby-b-sync
on:
  schedule:
    - cron: '12 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-passerby-b-JavaScript
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync passerby-b-JavaScript
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/passerby-b/JDDJ.git"
          source_branch: "main"
          destination_branch: "passerby-b"
          github_token: ${{ secrets.PAT }}
